### ISSUE TITLE
我是为了福利

### ISSUE THREAD

**Issue by haoXu1990** [Jack-Cherish/python-spider#1]
我想爬取ttp://www.biqukan.com 这个网站所有小说，然后自己写个小说app，能给我点意见吗

**Comment by Jack-Cherish** [comment]
@haoXu1990 我感觉可以先爬取它所有的小说文章地址链接，放入数据库，定期检查是否有新小说，有了再放入。通过这个url接口，手机APP就可以访问每个小说了。

**Comment by haoXu1990** [comment]
@Jack-Cherish  很感谢您的回复， 我也是考虑要么存所有小说的文本，要么存链接，存文本感觉数据太多了，爬取链接要方便点，只是需要在app端来处理html内容

**Comment by Jack-Cherish** [comment]
@haoXu1990 嗯嗯，不过这样对他们服务器的依赖较强。不过如果只是自己玩一玩，用一用，感觉这样就够了。

**Comment by Jack-Cherish** [comment]
@haoXu1990 来来来，更新了。邮箱走一个，发给你

**Comment by haoXu1990** [comment]
@Jack-Cherish  286089659@qq.com 走心了兄弟

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
