### ISSUE TITLE
12306抢票 error

### ISSUE THREAD

**Issue by zkl99999** [Jack-Cherish/python-spider#10]
等待验证码，自行输入...
购票页面开始...
循环点击查询... 第 1 次
no elements could be found with text "预订"
还没开始预订
循环点击查询... 第 2 次
Message: unknown error: Element <a href="javascript:" id="query_ticket" class="b
tn92s btn-disabled" shape="rect">...</a> is not clickable at point (1102, 15). O
ther element would receive the click: <th class="last" rowspan="1" colspan="1">.
..</th>
  (Session info: chrome=63.0.3213.3)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87a
f1),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by Jack-Cherish** [comment]
@zkl99999 加个延时吧。可能是网速不好，元素没有加载出来，就点击了。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
