### ISSUE TITLE
执行cartoon.py结果报错IndexError: list index out of range

### ISSUE THREAD

**Issue by JeannieWay** [Jack-Cherish/python-spider#106]
按照作者公众号上的教程练习爬取漫画的过程中，发现在执行cartoon.py时，总是运行了一会儿就会报错IndexError: list index out of range，按照网上的教程https://www.cnblogs.com/zhaoxinhui/p/12392438.html
修改了，原来只下载2%就会报错，加入except IndexError后下载进度到5%会报错，不知道是什么原因，可否有大佬相助解惑一下？非常感谢！
报错截图如下：
![image](https://user-images.githubusercontent.com/38314791/110908583-00d96d80-834a-11eb-8ddf-6da8eced5ea0.png)

**Comment by Jack-Cherish** [comment]
@JeannieWay 不太清楚，可能新增了反爬。
