### ISSUE TITLE
12306抢票报错

### ISSUE THREAD

**Issue by Hotsunrize** [Jack-Cherish/python-spider#14]
Message: unknown error: Element <a href="javascript:" id="query_ticket" class="btn92s" shape="rect">...</a> is not clickable at point (1112, 99). Other element would receive the click: <div class="dhx_modal_cover" style="display: inline-block;"></div>
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.10586 x86_64)

**Comment by Jack-Cherish** [comment]
应该是元素不对，找下提交元素位置，或者加个延时等待就好了 @Hotsunrize

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
