### ISSUE TITLE
VIP视频

### ISSUE THREAD

**Issue by fish1024** [Jack-Cherish/python-spider#15]
大神video_downloader目录下没有requirements.txt文件，python安装不了。
爱奇艺vip用软件出来的只有免费的6分钟吗？

**Comment by Jack-Cherish** [comment]
有这个文件的，你再看看。
软件那个早就没有维护了，就是一个demo。现在是网站解析了
http://cuijiahua.com/video/

**Comment by fish1024** [comment]
厉害了我的哥·····

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
