### ISSUE TITLE
大大帮忙看一看这是什么原因

### ISSUE THREAD

**Issue by hzc54188** [Jack-Cherish/python-spider#17]
![2](https://user-images.githubusercontent.com/24639554/38363634-f848a080-3907-11e8-947d-638bc693f5b0.png)

**Comment by Jack-Cherish** [comment]
@hzc54188 这个应该是没有匹配到，可能是增加了什么验证吧，比如ua，你可以试一试。

**Comment by Jack-Cherish** [comment]
@hzc54188 已修复
