### ISSUE TITLE
星级的服务，专业的技术

### ISSUE THREAD

**Issue by Jack-Cherish** [Jack-Cherish/python-spider#2]
邮箱留下，技术拿走。

**Comment by haoXu1990** [comment]
286089659@qq.com 感谢老铁！！！！！！

**Comment by haoXu1990** [comment]
@Jack-Cherish  源码看了，这个福利很好！

**Comment by Jack-Cherish** [comment]
@haoXu1990 感兴趣可以试试1024草榴去，哈哈。

**Comment by haoXu1990** [comment]
不能在多了怕翻车，技术重要。。。。

**Comment by sheseido** [comment]
154000588@qq.com  谢谢还有这神器

**Comment by Jack-Cherish** [comment]
@sheseido 已发

**Comment by sheseido** [comment]
@Jack-Cherish  哈哈 谢谢

**Comment by bluesgit** [comment]
bluesease@163.com, 谢谢老铁啊！

**Comment by Jack-Cherish** [comment]
@bluesgit 已发~

**Comment by 17853829** [comment]
感谢老铁，17853829@qq.com

**Comment by Jack-Cherish** [comment]
@17853829 老铁，差个follow。follow走一个

**Comment by xp-git** [comment]
362156887@qq.com 滴学生卡。。。。

**Comment by Jack-Cherish** [comment]
@xp-git 已发

**Comment by qinyang1018** [comment]
yczx27@163.com   开车技术

**Comment by Jack-Cherish** [comment]
@qinyang1018 已发，老铁差个follow，感觉车技不错，赏个follow呗。哈哈~

**Comment by qinyang1018** [comment]
@Jack-Cherish follow了  可以建个群交流下车技，交流交流爬虫

**Comment by Jack-Cherish** [comment]
@qinyang1018 怎奈时间不多，没精力经营啊。以后有机会的吧，哈哈。

**Comment by qinyang1018** [comment]
@Jack-Cherish 我看了下 这样一个一个的爬起来不是很方便  应该可以从列表改成批量爬取

**Comment by Jack-Cherish** [comment]
@qinyang1018 这就是个下载小工具，下载个视频用用。批量爬视频的我也有，用的scrapy。还有批量爬这些网站的别人发的帖子的图片。不过有bug，就是爬久了，下载几G视频后，会假死。所以就自己玩玩了，哈哈。

**Comment by qinyang1018** [comment]
@Jack-Cherish 批量爬的能给我个吗？

**Comment by Jack-Cherish** [comment]
@qinyang1018 发了，91的爬帖子图片的，有假死。文件保存路径在settings.py里设置下就行了。爬取视频的貌似让我删了，没找到。你可以试一试，挺好爬的。

**Comment by qinyang1018** [comment]
@Jack-Cherish 好的  谢了

**Comment by haiguanplayer** [comment]
214577708@qq.com滴（虽然不知道是啥

**Comment by Jack-Cherish** [comment]
@haiguanplayer 扎心了，老铁。福利仅限给了star和follow的老铁们。

**Comment by haiguanplayer** [comment]
好我follow下

2017-08-30 22:12 GMT+08:00 Jack Cui <notifications@github.com>:

**Comment by Jack-Cherish** [comment]
@haiguanplayer 感谢老铁，已发。

**Comment by WangShanpeng** [comment]
402729518@qq.com

**Comment by Jack-Cherish** [comment]
@WangShanpeng 你个逗逼....

**Comment by lianbo2006** [comment]
Please pub in the 'Little fresh meat' group!!!

**Comment by Jack-Cherish** [comment]
@lianbo2006 不敢不敢

**Comment by nigaea** [comment]
765854380@qq.com
这个现在貌似他会一段时间过期。感觉抖音有防爬策略了。
cp=afcd9f53ffd7e902e1&as=a1556a5e9fccb950dd，这个两个不同步的话就不能访问了。

**Comment by Jack-Cherish** [comment]
@nigaea 写完了就没有用，呃，这个是有可能的。我之前隔几天 还能的。

**Comment by nigaea** [comment]
求scrapy相关软件，研究学习中。能邮箱一些吗？
我的邮箱：765854380@qq.com

**Comment by Jack-Cherish** [comment]
@nigaea 呃，之前是给他们传的小工具。现在不好用了。抱歉~欢迎随时关注

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by dengbaoling** [comment]
22391496847@qq.com 感谢老铁

**Comment by Jack-Cherish** [comment]
@dengbaoling 活动停了，抱歉，好早之前的了。
