### ISSUE TITLE
抖音视频无法下载

### ISSUE THREAD

**Issue by wangwanjie** [Jack-Cherish/python-spider#22]
使用抖音升级版2 提示
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning) 应该是要 https 认证

**Comment by Jack-Cherish** [comment]
@wangwanjie 不是认证的问题，是接口更改了。
