### ISSUE TITLE
bilibili 里面  get_download_url函数返回的download_url为什么都是访问不了的地址？

### ISSUE THREAD

**Issue by midpushgogo** [Jack-Cherish/python-spider#33]

**Comment by Jack-Cherish** [comment]
@midpushgogo 访问不了？那个是视频的存储地址。

**Comment by midpushgogo** [comment]
我是直接复制url到浏览器里试的   但是durl字典里的 backup_url可以直接下载

**Comment by Jack-Cherish** [comment]
@midpushgogo 哦哦这个因该是备份的url，如果首选的url失效了，会用备份的，至于为啥不能浏览器直接下载，应该有一些参数验证。durl里的backup_url我没用过，不过可以测试下那个url下载快，就用哪个。
