### ISSUE TITLE
能帮忙写一个爬取和讯期货新闻标题和时间的python爬虫吗

### ISSUE THREAD

**Issue by xldistance** [Jack-Cherish/python-spider#4]
http://futures.hexun.com/focus，多谢了

**Comment by xldistance** [comment]
import requests
from bs4 import BeautifulSoup
from datetime import datetime,timedelta
from time import sleep
url = 'http://futures.hexun.com/focus/index.html'
res = requests.get(url)
# 使用UTF-8编码
res.encoding = 'GBK'

# 使用剖析器为html.parser
soup = BeautifulSoup(res.text, 'html.parser')
todaystr = datetime.strftime(datetime.today(),'%Y-%m-%d %H:%M:%S.%f')[5:10] #当前日期格式化成字符串取日期


def newspoint():
    #soup.select('.temp01')新闻目录位置
    for news in soup.select('.temp01'):
        li = news.select('li')  #标题目录
        for i in li:
            #新闻标题    
            title = i.text
            if todaystr in title:   #只取当天新闻
                todaytitle = title                 
            if '限产'in todaytitle or '停产' in todaytitle or '着火' in todaytitle or '检修' in todaytitle or '加息' in todaytitle or '降息' in todaytitle:
                print(todaytitle)

if __name__ == '__main__':
    while True:#5分钟执行一次
        newspoint()
        sleep(300)

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
