### ISSUE TITLE
百度文库的爬虫是不是炸了。。。

### ISSUE THREAD

**Issue by ZYSzys** [Jack-Cherish/python-spider#42]
![screen shot 2018-07-25 at 6 00 49 pm](https://user-images.githubusercontent.com/23313266/43194337-b23b15f8-9034-11e8-80fe-567b3fdca03a.png)
爬出来的result是空数组

**Comment by Jack-Cherish** [comment]
@ZYSzys 应该是没有匹配到，用另一个试试看。

**Comment by ZYSzys** [comment]
![screen shot 2018-07-26 at 8 46 30 pm](https://user-images.githubusercontent.com/23313266/43263164-048e2b84-9115-11e8-9bf3-8ddc1e501928.png)
貌似也炸了，生成的txt文件是空的

**Comment by Jack-Cherish** [comment]
@ZYSzys 换个链接试试。

**Comment by ZYSzys** [comment]
![screen shot 2018-07-27 at 10 57 11 pm](https://user-images.githubusercontent.com/23313266/43328408-7d8df948-91f0-11e8-8f39-94376fabee95.png)
竟然不是通用的，有的可以有的不行🤕。。

**Comment by Jack-Cherish** [comment]
@ZYSzys 嗯嗯，貌似有bug，这个后来就没维护了。
