### ISSUE TITLE
大佬，抖音爬虫的js程序是如何从页面原始js分析出来的，能不能在博客上分享下过程。

### ISSUE THREAD

**Issue by hnlisf** [Jack-Cherish/python-spider#43]
大佬，抖音爬虫的js程序是如何从页面原始js分析出来的，能不能在博客上分享下过程。谢谢！

**Comment by Jack-Cherish** [comment]
@hnlisf 这个不是我解析的。别人pull requests的。

**Comment by hnlisf** [comment]
了解，我想学习下这个，然后用重构下这个数字签名的程序，现在js加载页面越来越普遍了

**Comment by hnlisf** [comment]
了解，我想学习下这个，然后用python重构下这个数字签名的程序，现在js加载页面越来越普遍了

**Comment by Jack-Cherish** [comment]
@hnlisf 嗯，确实，用到签名的越来越多了。
