### ISSUE TITLE
抖音搜索接口变更

### ISSUE THREAD

**Issue by moqijiasudu** [Jack-Cherish/python-spider#47]
刚用了下抖音的爬虫，发现抖音搜索接口已变更 会为每个关键字生成两个token参数。不知如何破解，请大神帮忙看看有没有啥好方法。
抓包发现最新接口为http://aweme.snssdk.com/aweme/v1/general/search
会用到cookie判断是否登录
还有搜索关键字参数变化mas和as 参数都会变化
keyword=***&offset=0&mas=010abf2fd5bc52c15a2cccb755d17528ee1d793a0e0b26f18808de&as=a135dc16bc6edbd9022563

**Comment by Jack-Cherish** [comment]
@moqijiasudu 看最新版本的

**Comment by moqijiasudu** [comment]
douyin_pro.py 吗？配置了无头浏览器 运行 报错 应该还是那个搜索接口的问题。
/python-spider/douyin_pro.py", line 35, in get_video_urls
    aweme_count = html['user_list'][0]['user_info']['aweme_count']
KeyError: 'user_list'

**Comment by Jack-Cherish** [comment]
@moqijiasudu 看目录啊，目录有啊。

**Comment by moqijiasudu** [comment]
目录的3个都试过了.。。。还是有我刚才提到的问题。

**Comment by steven7851** [comment]
抖音的搜索api变更，我没有能力逆向出算法
可以参考这里 https://github.com/sweet8-asia/douyin-sign

**Comment by icesunx** [comment]
@steven7851 
你给的那两个也是旧算法啊，没有包括mas的……
旧算法已经能解出来了。
新算法的mas也有人解出来了，但是没有把key发出来：
https://bbs.pediy.com/thread-246360.htm

**Comment by steven7851** [comment]
@icesunx
在 https://github.com/sweet8-asia/douyin-sign 有一段说明
>在最新的SDK版本有了新的mas字段辅助校验，这个完全可以忽略，只要把查询串的version_code设置到169之前就可以跳过这个字段了。
另外aid为必填字段，其他和接口本身无关的字段都可去掉。

**Comment by icesunx** [comment]
@steven7851 
所以需要一个旧版本注册的账号就可以用了是吗

**Comment by steven7851** [comment]
@icesunx 
应该是吧，他是要付费买的，我也没用

**Comment by steven7851** [comment]
有人推出了免费的签名服务，有空时会新增依赖这服务来使用搜索API的版本
https://github.com/AppSign/douyin

**Comment by Jack-Cherish** [comment]
@steven7851 很强！

**Comment by icesunx** [comment]
@steven7851 这个厉害了

**Comment by kenshinji** [comment]
> 抖音的搜索api变更，我没有能力逆向出算法
> 可以参考以下project，都是需要付费获取的
> 
> * https://github.com/sweet8-asia/douyin-sign
> * https://github.com/lujqme/douyin

@steven7851 404了

**Comment by steven7851** [comment]
https://github.com/bzkj-tech/douyin-api
