### ISSUE TITLE
滑动验证码，我参照你的做了一个，遇到一些问题，有时间时候能否帮忙看看，谢谢

### ISSUE THREAD

**Issue by sys0613** [Jack-Cherish/python-spider#49]
https://github.com/sys0613/python-spider/tree/master/geetest我暂时传到我的库了，等弄好了，再往你的库push，目前工商网站滑块不能测试，我就采用geetest官网的测试页面进行测试，点击登录，获取滑块图片时，我从fiddler抓包效果和说明我都写出来了。
我不太懂js和css，我想让你简单帮我说下流程。我现在不知道怎么往下走，获取到完整验证码图片，和有缺口的验证码图片了。
我现在有两个问题，想让你帮帮忙，谢谢。具体内容我都写到我github网址文件夹了。
问题1，我第一个请求访问的网址是不是根据登录页面中的js函数计算出来的？（我目前看不懂js）
问题2，我请求5和请求7中的乱序图片是要根据请求3中的js进行重新组合，还是根据请求4中的css进行组合，才能得到一个完整的图片，和一个有缺口的图片？
谢谢了，我目前的弱项是js和css。我看你的工商网址验证码改了，就想试好geetest官网的，push上来，让大家能用。目前卡在这里了。

**Comment by sys0613** [comment]
我google浏览器不太好使，无法删除上面的问题，你先无视它吧，谢谢，我继续跟下js，貌似是这个页面加载了3个js。

**Comment by Jack-Cherish** [comment]
@sys0613 先给你个思路，就是获取这个图片这个，他是通过一堆图片组合好的，你先获取那些图片的url，然后根据这些图片的url，使用我开源的解密方法试一试，看能否合成正常的图片和缺口图片。先把这一步弄好。

**Comment by sys0613** [comment]
现在的问题是，我看到是组合后的图片，组合后网址是http://static.geetest.com/pictures/gt/d49a453dc/bg/236e50296.jpg，是个乱的，我怀疑这个和你工商那个不一样，你那个是给多个碎片的网址，然后我们组合成完整图片，这个是直接返回乱序的完整图片，但是通过css控制图片显示方式？？因为我这个抓包只是返回一个图片地址，就是http://static.geetest.com/pictures/gt/d49a453dc/bg/236e50296.jpg这个，这个打开是没有排序的。我猜测是不是html5语法，可以控制这个图片怎么显示？这个geetest网站的，没有你说的那么多碎片的url

**Comment by sys0613** [comment]
我现在的思路是读一读js，学一下，看看js干嘛了。然后主要看看里面这个css，还有html5语法中的cavens画布，他这里用的是html5的画布。因为这里没有那么多碎图片的url。

**Comment by Jack-Cherish** [comment]
@sys0613 嗯，这块搞懂，你这就相当于又进阶了一级，哈哈。

**Comment by sys0613** [comment]
2018-08-10：
定期更新下进展，也好使大家了解我尝试了什么方式，哪些方式是可行的，哪些方式是不可行的。

目前点击登录以后，抓包发现返回的是3张图片（滑块，无缺口图片的乱序，有缺口完整图片的乱序）
现在要做的事情，就是将乱序的两张图片，恢复成正常顺序的图片。
个人感觉是css样式搞的事情，查询了相关的css功能，感觉应该是使用了css sprite（也称css精灵）的功能。
css精灵可以控制只显示图片的一部分，其使用background-position参数来决定显示哪一部分。可以将一张完整图片，切割出来几个部分显示。目前仅仅怀疑是该css精灵在作怪，但在页面css中搜索background-position有些过多，正在一点点取出geetest中使用的css

**Comment by Jack-Cherish** [comment]
@sys0613 嗯嗯，很强。如果想开源，可以pull过来。

**Comment by sys0613** [comment]
@Jack-Cherish 嗯呢，等真能弄出来，再pull过来，现在各种尝试，乱糟糟的，没整理，周末去外地了，两天没弄。今天又弄了点。看了些css和js，点完登录，发现调用的是如下的js网址。应该是单独生成了一个滑动页面。现在正在跟这个js代码呢，用到jquery了，看点儿查点儿资料。呵呵，挺锻炼人的。试试看吧，真能弄出来的话，我再整理pull过来
http://www.geetest.com/type/libs/gt.js

**Comment by Jack-Cherish** [comment]
@sys0613 嗯嗯，好的。给力~！

**Comment by sys0613** [comment]
现在的问题是能拿到乱序图片。按照background-position恢复的不太对啊，是我自己一个像素一个像素扒的，有误差，css知识储备不足啊，尴尬。在原链接中取不出来现成的css图片恢复代码。自己的写的div总是有偏差。

**Comment by Jack-Cherish** [comment]
@sys0613 把js翻译一遍，应该就可以吧？

**Comment by sys0613** [comment]
@Jack-Cherish 我把js直接拿来用，是不行的。跟了几个js函数，太多了。跟不进去。就是没有你之前那个div，分割图像的明文了

**Comment by CrazyBunQnQ** [comment]
@Jack-Cherish 您好，这几天我也在做 GEETEST 验证码破解，参考您的代码，我解决了乱序图问题，并提交了代码，您看可以接受我的 pull request 吗？

![效果图](http://wx3.sinaimg.cn/large/a6e9cb00ly1fuv2grdkftg207s07z4e9.gif)

**Comment by Jack-Cherish** [comment]
@CrazyBunQnQ 好的，我Merge下。

**Comment by sys0613** [comment]
@CrazyBunQnQ 厉害，我去学习下

**Comment by sys0613** [comment]
@CrazyBunQnQ @Jack-Cherish  您好，有完整能运行的代码么？我看Jack-Cherish合入的geetest.py代码运行不起来呢。这个网站已经没有Geetest验证码了。麻烦CrazyBunQnQ给一个能运行的代码链接呗，多谢

**Comment by Jack-Cherish** [comment]
@sys0613 OTCBTC的交易网站，需要用到，你可以试下，或者等 @CrazyBunQnQ 发下也行。

**Comment by sys0613** [comment]
@Jack-Cherish 我去@CrazyBunQnQ 主页查看了，从他主页我先学习下，多谢了。我自己找个网站再测试下。请问他上面那个动态图片是怎么制作的啊？就是上面验证码滑动那个图片，谢谢

**Comment by sys0613** [comment]
我在http://www.geetest.com/type/网站，用CrazyBunQnQ 的def save_bg(driver, bg_path="bg.png", bg_class=bgImgClass):这个方法测试了一下，太厉害了，很简短的代码，直接越过乱序图片，出来的就是完整的全图，学习了。

**Comment by CrazyBunQnQ** [comment]
我只提交了方法，直接调用就好啦，一起加油~喜欢的话希望也能给我的项目点个星星~
