### ISSUE TITLE
这个12306.py怎么跑步起来

### ISSUE THREAD

**Issue by Heyxiang** [Jack-Cherish/python-spider#5]

**Comment by Jack-Cherish** [comment]
安装需要的第三方库，下载chromedriver.exe指定路径，就可以了。

**Comment by whuhit** [comment]
# cookies值得自己去找, 下面两个分别是沈阳, 哈尔滨
	starts = u"%u6C88%u9633%2CSYT"
	ends = u"%u54C8%u5C14%u6EE8%2CHBB"
这两个东西在哪找呀

**Comment by RainSilva** [comment]
先F12打开控制台 然后输入出发地和到达地后查询
在在一个NetWork下的cookies有
_jc_save_fromStation 出发地
_jc_save_toStation 到达地

**Comment by Heyxiang** [comment]
这个我弄好了，怎么设置抢指定车次的车票

**Comment by Jack-Cherish** [comment]
@Heyxiang 车次得自己抓包，看请求了。这里我没有弄呢。

**Comment by Jack-Cherish** [comment]
@whuhit 就像 @RainSilva 所说的，输入查询地点，然后点击查询按钮，抓包就可以看到这两个cookies值了。这个应该是有固定格式的，找到格式，然后建一个站点字典，做相应查找即可。以后也不用每次都抓包。

**Comment by Heyxiang** [comment]
通过这种调用浏览器方式 感觉会慢很多，可以直接做成刷票那种软件么，或者app @Jack-Cherish

**Comment by Jack-Cherish** [comment]
@Heyxiang 嗯，这样是慢很多，这仅仅是个小demo，代码也没有多少。那得用java写了，或者写个微信小程序？没有研究过，不过有不少这样的抢票软件，可以参考下。

**Comment by Heyxiang** [comment]
@Jack-Cherish  我会java 会写app  还没仔细研究那些抢票软件怎么写的

**Comment by Jack-Cherish** [comment]
@Heyxiang 具体的我也没有研究过，我这个小demo就是自己玩玩的。找个小众一点的app，用apktool反编译一个apk看看呢？

**Comment by menglingqian0218** [comment]
splinter模块貌似官网显示只能在python2上用吧

**Comment by Jack-Cherish** [comment]
@menglingqian0218 我是python3没有问题。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
