### ISSUE TITLE
archlinux下运行video_downloader.py出现界面都是乱码

### ISSUE THREAD

**Issue by greasynose** [Jack-Cherish/python-spider#50]
我是在archlinux下运行这个脚本，可以正常显示界面，除了标题栏中应用程序的标题是对的，其他界面元素与按钮、菜单上的中文都显示为小方框。
![tkinter](https://user-images.githubusercontent.com/3103735/44025532-0176e960-9f23-11e8-8393-1d188b1795fb.png)

**Comment by Jack-Cherish** [comment]
@greasynose 应该是字体库的问题，不支持汉字。
