### ISSUE TITLE
网易云音乐下载失败

### ISSUE THREAD

**Issue by grant36x** [Jack-Cherish/python-spider#55]
post_request函数一直返回post_request error，分析了一下是在执行get_song_url函数的时候产生的，不知道是什么原因？  
![image](https://user-images.githubusercontent.com/32955885/44346457-87967880-a4c8-11e8-8c6b-51e2db79d733.png)

**Comment by Jack-Cherish** [comment]
@grant36x 这个应该是请求的问题，可能更新了接口，我有时间看下。

**Comment by janpychou** [comment]
应该是调用接口太频繁，被识别为机器人了。
{'msg': 'Cheating', 'code': -460, 'message': 'Cheating'}
