### ISSUE TITLE
B站视频下载不全

### ISSUE THREAD

**Issue by PiaoRongZhen** [Jack-Cherish/python-spider#57]
python bilibili.py -d lex -k lexburner2009年的零 -p 1
我这么下载一个10分钟的视频，只能下载前6分钟

**Comment by Jack-Cherish** [comment]
@PiaoRongZhen 视频是分段的，这个代码只下载了第一个视频分段，需要下载两个分段视频，然后使用ffmpeg合并一下即可。

**Comment by Jack-Cherish** [comment]
@PiaoRongZhen 代码已更新。
