### ISSUE TITLE
抖音的用户视频下载失效了

### ISSUE THREAD

**Issue by icesunx** [Jack-Cherish/python-spider#65]
抓包看请求数据，里面的视频列表是空的，随便哪个用户都是
分享的原链接是有视频的

**Comment by steven7851** [comment]
我这里测试是正常的，能不能把你出现的信息复制上来看看？这样我才知道你的问题在哪

**Comment by hyzboy** [comment]
我也试了不行，报错在get_video_urls函中，获得html后，其中各列表信息都为空，所以uid获取直接出错。

{'log_pb': {'impr_id': '20181119154659010014054041364124'}, 'extra': {'logid': '20181119154659010014054041364124', 'now': 1542613619452, 'fatal_item_ids': []}, 'status_code': 0, 'qc': '', 'challenge_list': [], 'music_list': [], 'user_list': [], 'has_top_user': 0}

**Comment by tensafe** [comment]
{'challenge_list': [], 'status_code': 0, 'log_pb': {'impr_id': '20181119160653010014063199981E9F'}, 'has_top_user': 0, 'extra': {'now': 1542614814111, 'logid': '20181119160653010014063199981E9F', 'fatal_item_ids': []}, 'music_list': [], 'user_list': [], 'qc': ''}

**Comment by steven7851** [comment]
可能搜索api需要登录了吧，有空我把登录功能做出来，可能要后天过后，我先暂时改成直接用UID的方式下载

**Comment by Jack-Cherish** [comment]
@tensafe @hyzboy @icesunx 已经更新了，感谢@steven7851
