### ISSUE TITLE
12306订票

### ISSUE THREAD

**Issue by JNULYD** [Jack-Cherish/python-spider#75]
登陆成功后的跳转到的网址变为“https://kyfw.12306.cn/otn/view/index.html”了。需要修改一下原代码。
另外代码的这个地方“self.driver.find_by_id('').select(self.pz)”缺少了id选择器。

**Comment by JNULYD** [comment]
登陆成功后的跳转到的网址变为“https://kyfw.12306.cn/otn/view/index.html”了。需要修改一下原代码。
另外代码的这个地方“self.driver.find_by_id('').select(self.pz)”缺少了id选择器。

**Comment by Jack-Cherish** [comment]
@JNULYD 我这个就之前的小demo，要是真想弄下，可以看下这个项目[https://github.com/pjialin/py12306](https://github.com/pjialin/py12306)
