### ISSUE TITLE
some problems trouble me

### ISSUE THREAD

**Issue by honel521** [Jack-Cherish/python-spider#78]
Hello, master Cui.
有一个问题想请教一下，我的代码（功能是一个电商平台自动下单）在windows 平台上跑没问题。但是在Linux 系统上面跑，只能得到get请求，post请求就没有得到响应，似乎是禁止了平台操作。还望大佬支招。

**Comment by Jack-Cherish** [comment]
@honel521 可能需要个跳过认证，例如no-check之类的。或者header请求头伪造下windows下的。
