### ISSUE TITLE
小说的那个脚本貌似章节比较长的小说会报错，不显示下载进度

### ISSUE THREAD

**Issue by menglingqian0218** [Jack-Cherish/python-spider#8]
#我用的这个目录 网址 报错 一千多章的小说 http://www.biqukan.com/1_1094/
Traceback (most recent call last):
  File "D:/py17/爬虫/小说.py", line 137, in <module>
    name,numbers,url_dict = d.get_download_url()
  File "D:/py17/爬虫/小说.py", line 73, in get_download_url
    download_dict['第' + str(numbers) + '章 ' + names[1]] = download_url
IndexError: list index out of range

#这个列表貌似没把整个目录全部取下来 ，只取到1259章，实际到1260章
1277 1278 ['第1256', ' 帝戟']
1278 1279 ['第1257', ' 你敢骂我？']
1279 1280 ['第1258', ' 陨落']
1280 1281 ['第1259张 风波再起！']

Process finished with exit code 1

**Comment by Jack-Cherish** [comment]
@menglingqian0218 应该是章节匹配错了，早期的代码了。可能网站结构也稍作了修改。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by richmond99** [comment]
因为有些小说没有"章"这个字，导致下面这句话报错。
names = str(download_name).split('章')
蠢一点的做法是忽略没有章的章节，在这句之前加上
if ('章') in download_name:

**Comment by exxfzc** [comment]
下载了biqukan.py回来之后怎么用的?比如上面的网址 http://www.biqukan.com/1_1094/,要怎样修改biqukan.py?
