### ISSUE TITLE
京东晒单方法过期

### ISSUE THREAD

**Issue by ChanJeff123** [Jack-Cherish/python-spider#82]
line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
生成文件夹里面没图片

**Comment by zhangjiangkun** [comment]
club_headers  的值不对，修改即可。

**Comment by Jack-Cherish** [comment]
@ChanJeff123 楼上正解，参数的话，抓包核对下。
