### ISSUE TITLE
大佬，请教一下淘宝图片怎么爬？

### ISSUE THREAD

**Issue by Remember2018** [Jack-Cherish/python-spider#83]
总是要登录，请问大佬这个该怎么解决比较好，谢谢！

**Comment by Jack-Cherish** [comment]
@Remember2018 淘宝没有抓过，模拟登录后，带着session取抓也不行吗？

**Comment by Remember2018** [comment]
@Jack-Cherish 谢谢大佬回复！没有用过session，可能我电脑登陆过淘宝，爬虫时会记录吧。但是我自己没有操作过那个。不能爬淘宝，我也担心账号被禁用。

**Comment by Neroxiezi** [comment]
@Remember2018  我做了爬取淘宝的图片,  首先 如果是商品的 图片,我是先 拿到  商品的详情链接去爬去的, 详情链接 是 通过 商品优惠券 和 关键字 搜索 然后爬去的 。如果 是 需要登录, 是可以模拟登录的。

**Comment by Remember2018** [comment]
@Neroxiezi 谢谢大佬回复！之前一段时间在准备爬淘宝的。后来只是爬了京东的。京东还是比较友好的，也比较低调，希望京东越来越好！
