### ISSUE TITLE
VIP解析接口

### ISSUE THREAD

**Issue by LiuJieTan** [Jack-Cherish/python-spider#9]
大神，您会爬这个VIP解析接口吗
 http://api.baiyug.cn/vip/index.php?url=

**Comment by Jack-Cherish** [comment]
@LiuJieTan 我的个人网站有一些接口，审查元素，拿去用吧。http://cuijiahua.com/video/

**Comment by LiuJieTan** [comment]
谢谢，不过我是想学一些技术。

**Comment by Jack-Cherish** [comment]
@LiuJieTan 本地解析？这个就是用VIP帐号，解析视频地址，然后交给客户端播放。

**Comment by LiuJieTan** [comment]
恩，就是和您的爬爱奇艺原理一样，只是那个VIP接口分析的时候有个参数不知道是怎么来的

**Comment by Jack-Cherish** [comment]
@LiuJieTan 哦哦，你想下载啊。最好别弄了，弄了之后，这个解析地址基本就会不好使了，我以前不知道，应该是账号检测出来非法下载？然后就会有一阵子失效。

**Comment by Jack-Cherish** [comment]
@LiuJieTan Google插件有个Flash Download Media 用这个插件下载也很方便。

**Comment by LiuJieTan** [comment]
嗯呢

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by lylares** [comment]
国内主流的平台我都用PHP实现了的，用VIP账号模拟登陆然后拿到地址就可以了，这种做法自己玩玩可以，其实开个会员一个月也花不了多少钱。。。
