### ISSUE TITLE
ModuleNotFoundError: No module named 'cartoon'

### ISSUE THREAD

**Issue by znq1994** [Jack-Cherish/python-spider#92]
C:\Users\panda\Desktop\cartoon>C:/Users/panda/AppData/Local/Programs/Python/Python37/python.exe c:/Users/panda/Desktop/cartoon/cartoon/cartoon/spiders/comic_spider.py
Traceback (most recent call last):
  File "c:/Users/panda/Desktop/cartoon/cartoon/cartoon/spiders/comic_spider.py", line 4, in <module>
    from cartoon.items import ComicItem
ModuleNotFoundError: No module named 'cartoon'

**Comment by Jack-Cherish** [comment]
@znq1994 就是没有找到cartoon这个文件夹，可以创建一个__init__.py

**Comment by RobinJCY** [comment]
我今天也发现这个问题，  from Cartoon.items import ComicItem
ModuleNotFoundError: No module named 'Cartoon'
Process finished with exit code 1
如果只是最初测试运行打印每章链接和内容名字是可以运行没报错的，但是后来进一步在comic.py里加入更多代码时再运行就出现以上一样的报错，如果说创建一个__init__.py，但是它不是默认是空的吗？不知道怎么创建？
