### ISSUE TITLE
关于百度文库的问题

### ISSUE THREAD

**Issue by Belief28** [Jack-Cherish/python-spider#93]
兄弟，你是怎么找到那个json接口的

**Comment by Jack-Cherish** [comment]
@Belief28 有点久远，忘记了，不过一定是fiddler抓包过滤看的。

**Comment by Belief28** [comment]
好的，不在js里面是吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jack Cui"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 下午3:43
收件人:&nbsp;"Jack-Cherish/python-spider"<python-spider@noreply.github.com&gt;;
抄送:&nbsp;"sunchunqi"<1308603525@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Jack-Cherish/python-spider] 关于百度文库的问题 (#93)




@Belief28 有点久远，忘记了，不过一定是fiddler抓包过滤看的。

**Comment by Jack-Cherish** [comment]
@Belief28 应该是的

**Comment by Belief28** [comment]
是在js中找到那个接口的是吧





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jack Cui"<notifications@github.com&gt;; 
发送时间: 2020年3月4日(星期三) 晚上9:03
收件人: "Jack-Cherish/python-spider"<python-spider@noreply.github.com&gt;; 
抄送: "sunchunqi"<1308603525@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Jack-Cherish/python-spider] 关于百度文库的问题 (#93)




@Belief28 应该是的

**Comment by Jack-Cherish** [comment]
@Belief28 记不太清楚了，普通的页面没有，就只能去js里翻了。
