### ISSUE TITLE
python-spider/2020/zycjw/video_download.py 

### ISSUE THREAD

**Issue by YahuGao** [Jack-Cherish/python-spider#96]
直接使用ffmpeg下载采集到的视频会遇到403 问题：
`[https @ 0x55f25e719180] HTTP error 403 Forbidden
https://youku.com-youku.net/20180614/11920_4c9e1cc1/index.m3u8: Server returned 403 Forbidden (access denied)
`
请问这类问题，有解决的办法吗？有的话，要如何解决？谢谢。

**Comment by Jack-Cherish** [comment]
403，远程断服务器断开了，并发量太大了。没有特别好的办法，等待一会儿重新下。

**Comment by YahuGao** [comment]
好吧，多谢。
