### ISSUE TITLE
调别人的api获取下载地址  这也好意思叫爬虫吗？？？

### ISSUE THREAD

**Issue by incubus-ohy** [Jack-Cherish/python-spider#99]
调别人的api获取下载地址  这也好意思叫爬虫吗？？？

**Comment by pythonal** [comment]
？？？？你发错人了吧


| |
tewecang
|
|
邮箱：tewecang@126.com
|

Signature is customized by Netease Mail Master

在2020年07月24日 09:43，incubus-ohy 写道：

调别人的api获取下载地址 这也好意思叫爬虫吗？？？

**Comment by incubus-ohy** [comment]
> ？？？？你发错人了吧 | | tewecang | | 邮箱：tewecang@126.com | Signature is customized by Netease Mail Master 在2020年07月24日 09:43，incubus-ohy 写道： 调别人的api获取下载地址 这也好意思叫爬虫吗？？？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

难道获取bilibli下载地址是它解析的？如果我掉别人的接口了  这项目还有什么意义

**Comment by Jack-Cherish** [comment]
@incubus-ohy 看文章了吗？
